INDEX_HTML = r"""<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>HPD OCR Studio - PaddleOCR-VL 1.6</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"></script>
  <style>
    body{font-family:Inter,sans-serif}.hidden{display:none!important}.dropzone{border:2px dashed #cbd5e1;transition:.2s}.dropzone:hover,.dropzone.dragover{border-color:#2563eb;background:#eff6ff}.primary{background:linear-gradient(135deg,#2563eb,#1d4ed8);box-shadow:0 8px 22px #2563eb40}.primary.ready{background:linear-gradient(135deg,#059669,#047857)}.tab.active{background:#eff6ff;color:#1d4ed8;font-weight:600}.block-card,.ocr-box{transition:.15s}.block-card:hover,.block-card.active{border-color:#3b82f6;background:#eff6ff;box-shadow:0 0 0 1px #bfdbfe}.stage{background-color:#e2e8f0;background-image:linear-gradient(45deg,#cbd5e1 25%,transparent 25%),linear-gradient(-45deg,#cbd5e1 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#cbd5e1 75%),linear-gradient(-45deg,transparent 75%,#cbd5e1 75%);background-size:16px 16px;background-position:0 0,0 8px,8px -8px,-8px 0}#result-canvas{display:block;max-width:100%;height:auto}#overlay{position:absolute;inset:0;width:100%;height:100%}.ocr-box{cursor:pointer;fill-opacity:.1;stroke-width:2;vector-effect:non-scaling-stroke}.ocr-box:hover,.ocr-box.active{fill-opacity:.3;stroke-width:3}pre{white-space:pre-wrap;word-break:break-word}
  </style>
</head>
<body class="min-h-screen bg-slate-50 text-slate-900">
  <header class="sticky top-0 z-30 border-b bg-white/95 backdrop-blur"><div class="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-5"><div class="flex items-center gap-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-lg font-bold text-white">VL</div><div><h1 class="font-bold">HPD OCR Studio</h1><p class="text-xs text-slate-500">PaddleOCR-VL 1.6 · Block visualization</p></div></div><div class="flex items-center gap-3 text-xs"><span class="flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1.5"><i class="h-2 w-2 animate-pulse rounded-full bg-emerald-500"></i><span id="status">Đang kết nối…</span></span><a class="font-medium text-blue-600" href="/docs" target="_blank">API Docs ↗</a></div></div></header>
  <main class="mx-auto grid max-w-[1500px] grid-cols-1 gap-5 p-5 lg:grid-cols-12">
    <aside class="flex flex-col gap-4 lg:col-span-4">
      <section class="rounded-2xl border bg-white p-5 shadow-sm">
        <div class="mb-4 flex items-center justify-between"><div><h2 class="font-semibold">Tải tài liệu</h2><p class="text-xs text-slate-500">JPG, PNG, WebP hoặc PDF</p></div><div class="flex gap-1"><button id="btn-sample-jpg" class="rounded border border-blue-200 bg-blue-50 px-2 py-1 text-[11px] text-blue-700">JPG mẫu</button><button id="btn-sample-pdf" class="rounded border border-red-200 bg-red-50 px-2 py-1 text-[11px] text-red-700">PDF mẫu</button><button id="btn-sample-png" class="rounded border px-2 py-1 text-[11px]">PNG mẫu</button></div></div>
        <div id="dropzone" class="dropzone flex min-h-[310px] cursor-pointer flex-col items-center justify-center overflow-hidden rounded-xl p-4 text-center"><input id="file-input" class="hidden" type="file" accept=".jpg,.jpeg,.png,.webp,.pdf,image/*,application/pdf"><div id="prompt"><div class="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-2xl">↑</div><p class="text-sm font-semibold">Kéo thả tệp vào đây</p><p class="mt-1 text-xs text-slate-500">hoặc <span class="text-blue-600">chọn từ máy tính</span></p></div><img id="preview" class="hidden max-h-[270px] max-w-full rounded-lg object-contain"><div id="pdf-preview" class="hidden flex-col items-center gap-2"><canvas id="pdf-canvas" class="max-h-[250px] max-w-full rounded-lg border bg-white"></canvas><p id="pdf-info" class="text-xs text-slate-600"></p></div></div>
        <button id="submit" class="primary mt-4 flex w-full items-center justify-center gap-2 rounded-xl py-3.5 font-semibold text-white disabled:opacity-70"><span id="submit-icon">⚡</span><span id="submit-spinner" class="hidden animate-spin">◌</span><span id="submit-text">Chọn tệp để bắt đầu OCR</span></button><p id="file-info" class="mt-2 truncate text-center text-xs text-slate-500">Chưa chọn tệp</p>
      </section>
      <section class="rounded-xl border bg-white p-4 text-xs text-slate-600"><div class="mb-2 flex justify-between"><strong>Chú thích block</strong><span class="rounded bg-blue-100 px-2 py-.5 font-mono text-blue-700">0.9B BF16</span></div><div class="grid grid-cols-2 gap-2"><span>🟦 Văn bản</span><span>🟩 Bảng</span><span>🟪 Công thức</span><span>🟧 Biểu đồ</span></div></section>
    </aside>
    <section class="min-w-0 lg:col-span-8"><div class="flex min-h-[700px] flex-col rounded-2xl border bg-white shadow-sm">
      <div class="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div class="flex rounded-xl bg-slate-100 p-1 text-xs"><button id="tab-blocks" class="tab active rounded-lg px-3 py-2">Block & OCR</button><button id="tab-text" class="tab rounded-lg px-3 py-2 text-slate-600">Văn bản</button><button id="tab-json" class="tab rounded-lg px-3 py-2 text-slate-600">JSON</button></div><div class="flex gap-2"><span id="block-count" class="hidden rounded-full bg-blue-50 px-2.5 py-1 text-xs text-blue-700"></span><button id="copy" class="rounded-lg border px-3 py-1.5 text-xs">Sao chép</button><button id="download" class="rounded-lg border px-3 py-1.5 text-xs">Tải xuống</button></div></div>
      <div class="flex min-h-0 flex-1 flex-col overflow-hidden p-4">
        <div id="empty" class="flex flex-1 flex-col items-center justify-center text-center text-slate-400"><div class="mb-3 text-5xl">▧</div><p class="text-sm font-medium">Kết quả OCR sẽ xuất hiện tại đây</p><p class="mt-1 max-w-sm text-xs">Khung block trên tài liệu và nội dung nhận dạng được đặt cạnh nhau để dễ đối chiếu.</p></div>
        <div id="loading" class="hidden flex flex-1 flex-col items-center justify-center gap-3"><div class="h-11 w-11 animate-spin rounded-full border-4 border-blue-100 border-t-blue-600"></div><p class="text-sm font-medium">Đang phân tích bố cục và nhận dạng…</p><p id="timer" class="font-mono text-xs text-slate-500">0.0s</p></div>
        <div id="content-blocks" class="hidden min-h-0 flex-1 flex-col gap-4 xl:flex-row"><div class="flex min-h-[440px] min-w-0 flex-[1.35] flex-col overflow-hidden rounded-xl border bg-slate-100"><div class="flex h-11 items-center justify-between border-b bg-white px-3 text-xs"><strong>Tài liệu có đánh dấu block</strong><div id="page-controls" class="hidden items-center gap-1"><button id="prev" class="rounded border px-2 py-1">←</button><span id="page-label" class="min-w-[68px] text-center"></span><button id="next" class="rounded border px-2 py-1">→</button></div></div><div class="stage flex flex-1 items-start justify-center overflow-auto p-4"><div id="canvas-wrap" class="relative shadow-xl"><canvas id="result-canvas" class="bg-white"></canvas><svg id="overlay"></svg></div></div></div><div class="flex min-h-[320px] min-w-0 flex-1 flex-col overflow-hidden rounded-xl border"><div class="flex h-11 items-center justify-between border-b bg-slate-50 px-3"><strong class="text-xs">Kết quả theo block</strong><span id="visible-count" class="text-[11px] text-slate-500"></span></div><div id="block-list" class="flex max-h-[570px] flex-1 flex-col gap-2 overflow-y-auto p-3"></div></div></div>
        <div id="content-text" class="hidden flex-1 overflow-auto rounded-xl border bg-slate-50 p-5"><pre id="text-output" class="text-sm leading-7"></pre></div><div id="content-json" class="hidden flex-1 overflow-auto rounded-xl bg-slate-950 p-5"><pre id="json-output" class="font-mono text-xs leading-6 text-emerald-400"></pre></div>
      </div><div id="meta" class="hidden flex-wrap justify-between gap-2 border-t px-5 py-3 text-xs text-slate-500"><div class="flex gap-3"><span id="timing"></span><span id="pages"></span></div><span id="model"></span></div>
    </div></section>
  </main>
<script>
if(window.pdfjsLib)pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const $=id=>document.getElementById(id),styles={text:{label:'Văn bản',color:'#2563eb',badge:'bg-blue-100 text-blue-700'},table:{label:'Bảng',color:'#059669',badge:'bg-emerald-100 text-emerald-700'},formula:{label:'Công thức',color:'#7c3aed',badge:'bg-violet-100 text-violet-700'},chart:{label:'Biểu đồ',color:'#d97706',badge:'bg-amber-100 text-amber-700'}};
let base64=null,fileName=null,dataUrl=null,isPdf=false,result=null,resultPdf=null,pageNo=1,tick=null;
fetch('/healthz').then(r=>r.json()).then(d=>$('status').textContent=`${d.model_id} (${d.status})`).catch(()=>$('status').textContent='Mất kết nối máy chủ');
function bytes(v){const raw=atob(v),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
$('dropzone').onclick=()=>$('file-input').click();$('file-input').onchange=e=>handle(e.target.files);$('dropzone').ondragover=e=>{e.preventDefault();$('dropzone').classList.add('dragover')};$('dropzone').ondragleave=()=>$('dropzone').classList.remove('dragover');$('dropzone').ondrop=e=>{e.preventDefault();$('dropzone').classList.remove('dragover');handle(e.dataTransfer.files)};
function handle(files){if(!files?.length)return;const f=files[0];fileName=f.name;isPdf=f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf');$('file-info').textContent=`${f.name} · ${(f.size/1024).toFixed(1)} KB`;$('prompt').classList.add('hidden');$('submit').classList.add('ready');$('submit-text').textContent=`Bắt đầu OCR · ${f.name}`;const reader=new FileReader();reader.onload=async e=>{dataUrl=e.target.result;base64=dataUrl.split(',')[1];if(isPdf){$('preview').classList.add('hidden');$('pdf-preview').classList.remove('hidden');$('pdf-preview').classList.add('flex');try{const pdf=await pdfjsLib.getDocument({data:bytes(base64)}).promise,p=await pdf.getPage(1),v=p.getViewport({scale:.65}),c=$('pdf-canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;$('pdf-info').textContent=`${f.name} · ${pdf.numPages} trang`}catch{$('pdf-info').textContent='Không thể xem trước PDF'}}else{$('pdf-preview').classList.add('hidden');$('pdf-preview').classList.remove('flex');$('preview').src=dataUrl;$('preview').classList.remove('hidden')}};reader.readAsDataURL(f)}
async function sample(url,name,type){try{const r=await fetch(url);if(!r.ok)throw Error('Không tải được tệp mẫu');handle([new File([await r.blob()],name,{type})])}catch(e){alert(e.message)}}
$('btn-sample-jpg').onclick=e=>{e.stopPropagation();sample('/sample-jpg','sample_vn_invoice.jpg','image/jpeg')};$('btn-sample-pdf').onclick=e=>{e.stopPropagation();sample('/sample-pdf','sample_vn_document.pdf','application/pdf')};$('btn-sample-png').onclick=e=>{e.stopPropagation();sample('/sample-image','sample_vn_invoice.png','image/png')};
function hide(){$('empty').classList.add('hidden');$('loading').classList.add('hidden');['blocks','text','json'].forEach(n=>$(`content-${n}`).classList.add('hidden'));$('meta').classList.add('hidden')}
$('submit').onclick=async()=>{if(!base64){$('file-input').click();return}$('submit').disabled=true;$('submit-icon').classList.add('hidden');$('submit-spinner').classList.remove('hidden');$('submit-text').textContent='Đang nhận dạng…';hide();$('loading').classList.remove('hidden');const start=Date.now();tick=setInterval(()=>$('timer').textContent=`${((Date.now()-start)/1000).toFixed(1)}s`,100);try{const r=await fetch('/v1/ocr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content_base64:base64,filename:fileName,mode:'vlm'})}),d=await r.json();if(!r.ok)throw Error(d.detail||'OCR thất bại');result=d;pageNo=1;resultPdf=isPdf?await pdfjsLib.getDocument({data:bytes(base64)}).promise:null;$('text-output').textContent=d.markdown||'(Không có văn bản)';$('json-output').textContent=JSON.stringify(d,null,2);const pc=Math.max(1,...(d.blocks||[]).map(b=>b.page||1));$('timing').textContent=`Thời gian: ${((Date.now()-start)/1000).toFixed(2)}s`;$('pages').textContent=`${pc} trang`;$('model').textContent=`Engine: ${d.model_id||'PaddleOCR-VL'}`;$('block-count').textContent=`${(d.blocks||[]).length} block`;$('block-count').classList.remove('hidden');$('meta').classList.remove('hidden');await show('blocks')}catch(e){$('empty').classList.remove('hidden');alert(`Lỗi: ${e.message}`)}finally{clearInterval(tick);$('loading').classList.add('hidden');$('submit').disabled=false;$('submit-icon').classList.remove('hidden');$('submit-spinner').classList.add('hidden');$('submit-text').textContent=`Bắt đầu OCR · ${fileName}`}};
async function show(type){if(!result)return;['blocks','text','json'].forEach(n=>{$(`tab-${n}`).classList.toggle('active',n===type);$(`content-${n}`).classList.add('hidden')});const c=$(`content-${type}`);c.classList.remove('hidden');if(type==='blocks'){c.classList.add('flex');await render(pageNo)}else c.classList.remove('flex')}
['blocks','text','json'].forEach(n=>$(`tab-${n}`).onclick=()=>show(n));
async function render(n){const c=$('result-canvas'),ctx=c.getContext('2d');if(resultPdf){const p=await resultPdf.getPage(n),base=p.getViewport({scale:1}),v=p.getViewport({scale:Math.min(1.5,900/base.width)});c.width=Math.round(v.width);c.height=Math.round(v.height);await p.render({canvasContext:ctx,viewport:v}).promise}else{const img=new Image();img.src=dataUrl;await img.decode();const s=Math.min(1,900/img.naturalWidth);c.width=Math.round(img.naturalWidth*s);c.height=Math.round(img.naturalHeight*s);ctx.drawImage(img,0,0,c.width,c.height)}draw(n,c.width,c.height);const count=resultPdf?resultPdf.numPages:Math.max(1,...result.blocks.map(b=>b.page||1));$('page-controls').classList.toggle('hidden',count<=1);$('page-controls').classList.toggle('flex',count>1);$('page-label').textContent=`${n} / ${count}`;$('prev').disabled=n<=1;$('next').disabled=n>=count}
function draw(n,w,h){const blocks=(result.blocks||[]).filter(b=>(b.page||1)===n),svg=$('overlay'),list=$('block-list');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML='';list.innerHTML='';$('visible-count').textContent=`${blocks.length} block trên trang`;blocks.forEach((b,i)=>{const key=`${n}-${b.order}-${i}`,s=styles[b.kind]||styles.text,box=b.bbox||{x0:0,y0:0,x1:1,y1:1},x=box.x0*w,y=box.y0*h,bw=(box.x1-box.x0)*w,bh=(box.y1-box.y0)*h,g=document.createElementNS('http://www.w3.org/2000/svg','g'),rect=document.createElementNS('http://www.w3.org/2000/svg','rect'),bg=document.createElementNS('http://www.w3.org/2000/svg','rect'),label=document.createElementNS('http://www.w3.org/2000/svg','text');g.dataset.key=key;rect.setAttribute('x',x);rect.setAttribute('y',y);rect.setAttribute('width',bw);rect.setAttribute('height',bh);rect.setAttribute('rx',3);rect.setAttribute('fill',s.color);rect.setAttribute('stroke',s.color);rect.setAttribute('class','ocr-box');bg.setAttribute('x',x);bg.setAttribute('y',Math.max(0,y-21));bg.setAttribute('width',34);bg.setAttribute('height',21);bg.setAttribute('fill',s.color);label.setAttribute('x',x+5);label.setAttribute('y',Math.max(15,y-6));label.setAttribute('fill','white');label.setAttribute('font-size',12);label.setAttribute('font-weight',700);label.textContent=`#${b.order+1}`;g.append(rect,bg,label);g.onclick=()=>select(key);svg.appendChild(g);const card=document.createElement('button');card.dataset.key=key;card.className='block-card w-full rounded-xl border border-slate-200 p-3 text-left';const conf=b.confidence==null?'—':`${Math.round(b.confidence*100)}%`;card.innerHTML=`<div class="mb-2 flex justify-between gap-2"><span class="rounded px-2 py-0.5 text-[11px] font-semibold ${s.badge}">#${b.order+1} · ${s.label}</span><span class="text-[11px] text-slate-400">${conf}</span></div><p class="whitespace-pre-wrap break-words text-sm leading-5 text-slate-700">${escapeHtml(b.text||'(Không có nội dung)')}</p><p class="mt-2 font-mono text-[9px] text-slate-400">[${box.x0.toFixed(2)}, ${box.y0.toFixed(2)}, ${box.x1.toFixed(2)}, ${box.y1.toFixed(2)}]</p>`;card.onclick=()=>select(key);list.appendChild(card)});if(!blocks.length)list.innerHTML='<div class="m-auto p-6 text-xs text-slate-400">Không có block trên trang này.</div>'}
function select(key){document.querySelectorAll('[data-key]').forEach(e=>e.classList.toggle('active',e.dataset.key===key));document.querySelector(`#block-list [data-key="${key}"]`)?.scrollIntoView({behavior:'smooth',block:'nearest'})}function escapeHtml(v){const e=document.createElement('div');e.textContent=v;return e.innerHTML}
$('prev').onclick=async()=>{if(pageNo>1)await render(--pageNo)};$('next').onclick=async()=>{const count=resultPdf?.numPages||1;if(pageNo<count)await render(++pageNo)};
$('copy').onclick=async()=>{if(!result)return;const json=!$('content-json').classList.contains('hidden');await navigator.clipboard.writeText(json?JSON.stringify(result,null,2):result.markdown);$('copy').textContent='Đã sao chép';setTimeout(()=>$('copy').textContent='Sao chép',1200)};$('download').onclick=()=>{if(!result)return;const json=!$('content-json').classList.contains('hidden'),content=json?JSON.stringify(result,null,2):result.markdown,ext=json?'json':'txt',url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`${(fileName||'ocr_result').replace(/\.[^/.]+$/,'')}_result.${ext}`;a.click();URL.revokeObjectURL(url)};
</script></body></html>"""
